version: "3.7"
services:

  mongodb-dev:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: datasets # database name to give
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    container_name: mongodb-database
    ports:
      - "27017-27019:27017-27019"
  mapreduce:
    image: assignment2/mapreduce:latest
    restart: always
    depends_on:
      - mongodb-dev
    container_name: mapreduce
    ports:
      - "8080:8080"









